site_name: Container inventory legacy app
repo_url: https://github.com/ibm-cloud-architecture/refarch-container-inventory
nav:
  - Introduction: index.md
  - Development approach:
    - Create foundations: creatingApp.md
    - Apply TDD: tdd.md
  - Solution Deployments:
    - Run locally: /#build-and-run

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
