site_name: Container inventory legacy app
repo_url: https://github.com/ibm-cloud-architecture/refarch-container-inventory
nav:
  - Introduction: index.md
  - Integrations:
    - MQ - Kafka: mq-kafka.md
    - CDC - Kafka: cdc.md
    - Postgres - Debezium to kafka: debezium-postgresql.md
    - Event Streams - Debezium: eventstreams-debezium.md
  - Solution Deployments:
    - Deploy and run locally: run-local.md
    - Deploy and run on Openshift: openshift.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
